#+TITLE: Curriculum Vitae
#+AUTHOR: Marco Bardelli
#+EMAIL: bardelli.marco@gmail.com
#+MACRO: ADDRESS via Pontida, 4 40132 BO
#+LANGUAGE: it

#+OPTIONS: toc:nil date:nil num:nil

#+OPTIONS: texht:nil
#+LATEX_CLASS: resume
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: \usepackage[left=0.75in,top=0.6in,right=0.75in,bottom=0.6in]{geometry}

#+LATEX: \hfil
#+ATTR_LATEX: :center
#+NAME: tbl:info-recapiti
|                                    <r40> |
|                    nazionalità: Italiana |
|                 domicilio: {{{ADDRESS}}} |
|                      cell. : 328-5753263 |
|                      e-mail: {{{EMAIL}}} |


* Anagrafica							   :noexport:
  Nato a Reggio Emilia il 23/10/1982, Italia

  Residente in {{{ADDRESS}}}

  Stato civile celibe


* Obiettivi
  Apprendere nuovi metodi e linguaggi di programmazione.
  Acquisire esperienza sulla programmazione ed amministrazione
  di Sistema (in particolare sistemi unix-like).

  Sviluppare applicazioni e sistemi informatici utili e liberi,
  in particolare nell'ambito della domotica e del mobile.

* Istruzione:

** 2010 Alma Mater Studiorum - Universit@'a di Bologna

    Master of free and open source software technologies

    Il progetto conclusivo del master consisteva nella
    realizzazione di un sistema basato su D-Bus (IPC System)
    per la ricerca di torrent files attraverso vari motori di ricerca.

** 2008 Alma Mater Studiorum - Università di Bologna

   Laurea in Informatica Classe 26 Scienze e Tecnologie Informatiche

   La tesi finale “Privacy nei sistemi basati sul Kernel Linux”.

   Il progetto di tesi consisteva nella modifica del ProcFS
   all' interno del kernel Linux per rendere private
   le attività (processi) dei vari utenti del sistema.

** 2001 Istituto Tecnico Commerciale "G. Scaruffi" - Reggio Emilia

    Diploma di Perito commerciale, ragioniere, programmatore

* Esperienze lavorative:

** 2013 - Presente Araknos srl
   Responsabile di sviluppo della piattaforma, gestisco e scrivo
   software in una distribuzione Red-Hat based per coordinare un framework di
   macchine durante l'esecuzione del SIEM+ distribuito Akab2.
   Per lo sviluppo dell'applicativo Akab2 mi sto occupando del frontend web basato su
   Django.

** 2011 - 2013 Aderit srl
   Parte del team fondatore dell'azienda. Dopo l'esperienza di programmatore software
   ritorno alla progettazione, amministrazione, monitoraggio e manutenzione dei sistemi
   informatici. L'attivit@'a core dell'impresa si concentra sull'offerta di soluzioni per
   un'infrastruttura informatica in cloud computing e sullo sviluppo di siti e portali web.@*
   Parallelamente allo svolgimento delle mansioni di tecnico informatico, una componente
   importante della mia posizione è l'attività di ricerca e sviluppo, atta a proporre
   soluzioni innovative per la gestione efficace delle problematiche che
   l'infrastruttura informatica di una media impresa comporta.@*
   In questo ambito, ho progettato e realizzato un sistema per automatizzare
   il deployment dei servizi d'infrastruttura informatica su macchine virtuali in cloud,
   quali posta e web server sicuri utilizzando SSL/TLS (crittografia).@*
   Altre attività svolte:@*

   - l'implementazione di servizi di posta elettronica con anti-spam e anti-virus
     utilizzando Postix, Spamassassin e ClamAV;@*
   - la realizzazione di sistemi groupware (per rendere possibile il lavoro in gruppo), che
     includono:
     1. la webmail utilizzando Roundcube;@*
     2. CalDAV Server utilizzando DAViCal;@*
     3. rubrica contatti utilizzando OpenLDAP;@*
     4. Instant Messaging (xmpp) utilizzando ejabberd.@*

** 2010 - 2011 Servabit srl
   Analista sviluppatore software@*
   Due sono le aree principali in cui sono stato maggiormente coinvolto:
   1. Sviluppo web;
   2. sistemi ERP (enterprise resource planning).

   Con riferimento alla prima, ho coordinato il team informatico nello
   sviluppo di un portale multisito per una Fondazione bolognese,
   integrando il framework Django ed il software OpenERP.
   La seconda area vedeva il coinvolgimento nella progettazione e nello
   sviluppo di sistemi ERP per le knowledge companies. Lavoro svolto in
   un team formato da economisti, analisti ed informatici.
   Il progetto presupponeva un'approfondita conoscenza del software OpenERP,
   sviluppato in linguaggio python.

** 2008 - 2010 Istituti Ortopedici Rizzoli
   Il compito principale riguardava l' amministrazione dei
   sistemi Windows e GNU/Linux. I miei compiti principali
   includevano:
    - la configurazione router e firewall all'interno di reti
      miste (wired/wireless), utilizzando iptables e netfilter;
    - la configurazione e manutenzione dei server di calcolo;
    - l'implementazione di file-sharing su file system crittografato
      utilizzando il software LUKS (Linux Unified Key Setup),
      Samba (SMB/CIFS), OpenVPN (Virtual Private Network), GnuPG.

** 2006 Tirocinio universitario - Bologna
   Realizzazione di un sistema di monitoraggio di
   server remoti (Imola e Bologna) con tecnologie SNMP,
   volti a tenere sotto controllo le prestazioni di CPU, hard disk
   e traffico di rete, con sistema di alerting via e-mail.

** 1999 Stage presso uno studio associato di commercialisti
   della durata di 40 gg. non retribuito.
   Facchino per tre mesi. Vari lavori a tempo determinato
   tramite agenzie interinali. Postino per 4 mesi.
   Sviluppo di un sistema di monitoraggio di rete, presso
   il CED dell'ospedale Maggiore (Azienda USL di Bologna).
   Dal 2008 collaboro continuativamente con il
   Laboratorio di Tecnologia Medica degli Istituti
   Ortopedici Rizzoli in qualit@'a di amministratore di
   sistemi informatici.



* Interessi:							   :noexport:
  Informatica (in particolare software libero e strumenti liberi
  per un'informazione libera).

  CEDET (Collection of Emacs Development Environment Tools).

  Karate stile Shotokan.
